/*           CRTCMD     CMD(LANDXAPPO/MNU060C) +                   */
/*                      PGM(*LIBL/MNU060C) +                       */
/*                      SRCFILE(LANDXAPPS/QCMDSRC) +               */
/*                      SRCMBR(MNU060C) +                          */
/*                      TEXT('      Display User Menus') +         */
/*                      MODE( +                                    */
/*                        *ALL) +                                  */
/*                      ALLOW( +                                   */
/*                        *ALL) +                                  */
/*                      MAXPOS(*NOMAX) +                           */
/*                      PMTFILE(*NONE) +                           */
/*                      HLPSCHIDX(*NONE) +                         */
/*                      HLPPNLGRP(*NONE) +                         */
/*                      HLPID(*NONE)                               */

             CMD        PROMPT('      Display User Menus')
