/*           CRTCMD     CMD(LANDXAPPO/MNU010C) +                   */
/*                      PGM(*LIBL/MNU010C) +                       */
/*                      SRCFILE(LANDXAPPS/QCMDSRC) +               */
/*                      SRCMBR(MNU010C) +                          */
/*                      TEXT('  Work with User Menu Details') +    */
/*                      MODE( +                                    */
/*                        *ALL) +                                  */
/*                      ALLOW( +                                   */
/*                        *ALL) +                                  */
/*                      MAXPOS(*NOMAX) +                           */
/*                      PMTFILE(*NONE) +                           */
/*                      HLPSCHIDX(*NONE) +                         */
/*                      HLPPNLGRP(*NONE) +                         */
/*                      HLPID(*NONE)                               */

             CMD        PROMPT('  Work with User Menu Details')
